// RemittanceRouter contract (formerly Vault)
export const VAULT_CONTRACT_ID = 'CALUMWUGTN2STIK2CUUOGWUENIM354J5YCBZHACRY6HOUVCJWH5GB6EW';
// ExchangeLedger contract (formerly Token)
export const TOKEN_CONTRACT_ID = 'CCE6P2J7TGH7ALYNK7XP6GA3FLXJ4IZDOHXRVNAOHPJHQSB52HLPV7GW';
export const REMITTANCE_ROUTER_ID = 'CALUMWUGTN2STIK2CUUOGWUENIM354J5YCBZHACRY6HOUVCJWH5GB6EW';
export const EXCHANGE_LEDGER_ID = 'CCE6P2J7TGH7ALYNK7XP6GA3FLXJ4IZDOHXRVNAOHPJHQSB52HLPV7GW';
export const RPC_URL = 'https://soroban-testnet.stellar.org';
export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
